# Generated by Django 2.0.7 on 2018-07-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('customauth', '0002_auto_20180715_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
