# Generated by Django 2.0.7 on 2018-08-12 13:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajankohtaista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsikko', models.CharField(max_length=200)),
                ('kuvaus', models.TextField(max_length=1000)),
                ('teksti', tinymce.models.HTMLField()),
                ('pvm', models.DateTimeField(default=datetime.datetime.now)),
                ('tekija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ajankohtaista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kesateatteri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsikko', models.CharField(max_length=100)),
                ('sisalto', tinymce.models.HTMLField()),
                ('paivitetty', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Kesateatteri_naytelma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('esittaja', models.CharField(max_length=100)),
                ('sisalto', tinymce.models.HTMLField()),
                ('naytos_alku', models.DateField()),
                ('naytos_loppu', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tapahtuma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsikko', models.CharField(max_length=200)),
                ('kuvaus', models.TextField(max_length=1000)),
                ('teksti', tinymce.models.HTMLField()),
                ('pvm', models.DateTimeField(default=datetime.datetime.now)),
                ('tekija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tapahtumat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valokuva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsikko', models.CharField(max_length=100)),
                ('kuvaus', models.TextField(default=None, max_length=1000)),
                ('kuva', filebrowser.fields.FileBrowseField(max_length=3000, verbose_name='Kuva')),
                ('pvm', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
