# Generated by Django 2.0.7 on 2018-07-15 22:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('soikka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajankohtaista',
            name='pvm',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 22, 41, 37, 108138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ajankohtaista',
            name='teksti',
            field=models.TextField(blank=True),
        ),
    ]
