# Generated by Django 2.0.7 on 2018-07-15 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soikka', '0002_auto_20180716_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajankohtaista',
            name='pvm',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
