# Generated by Django 2.0.7 on 2018-07-15 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soikka', '0003_auto_20180716_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajankohtaista',
            name='pvm',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
