# Generated by Django 2.0.7 on 2018-07-24 10:05

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('soikka', '0004_auto_20180716_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valokuva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsikko', models.CharField(max_length=100)),
                ('kuvaus', models.TextField(max_length=1000)),
                ('kuva', models.ImageField(default=None, upload_to='kuvat')),
                ('pvm', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='ajankohtaista',
            name='teksti',
            field=tinymce.models.HTMLField(),
        ),
    ]
